### ISSUE TITLE
Request: add a tag for current (most recent) devel version

### ISSUE THREAD

**Issue by vga101** [hilbert/hilbert-heartbeat#11]
We use the current (most recent) commit from devel, 56fd0636df4686dd66e8f1cbf6cfdb0df4987212, for the interactives. Using hilbert-heartbeat as submodules within the interactives is simpler when we can refer to a tag.

**Comment by malex984** [comment]
current tag v0.2.0 : https://github.com/hilbert/hilbert-heartbeat/releases/tag/v0.2.0
