### ISSUE TITLE
Can the automatic heartbeat work in an iframe environment?

### ISSUE THREAD

**Issue by porst17** [hilbert/hilbert-heartbeat#12]
The automatic heartbeat just uses an interval timer that puts heartbeat events into the event queue on a regular basis. Usually, this means that the heartbeat script will be included and initialized from the web page it is supposed to monitor.

However, modifying the code of web pages might not be possible in some cases and the question is if it is possible to put the heartbeat code into a separate web page that includes the main page via a `<frame>` or `<iframe>`.

Of course, this only makes sense if the automatic heartbeat is used. If the web page in question wants to send proper heartbeats based on some health check, it needs to call the heartbeat methods directly.

**Comment by porst17** [comment]
Until now I thought that different frames would have separete event queues in the browser. But I just testing this in a simple `<iframe>` environmnet:
```
window.setInterval(function() {console.log("outer frame event");},500);
window.frames[0].setTimeout(function(){console.log("iframe event")},500);
window.frames[0].setTimeout(function(){while(true){}},750);
```
It prints out 
```
outer frame event
iframe event
```
and then the `<iframe>` goes into the infinite loop.

This also affects the outer frame. No further timer events are executed. I tested it in Firefox 58 and Chrome 63.

So using an `<iframe>` _seems_ to work. But I am not so confident that I didn't miss something. Opinions?

**Comment by porst17** [comment]
As @elondaits pointed out elsewhere, using `<iframe>`s may result in a big performance hit (probalby due to the additional compositing work?). Is this also true for regular frames?

Because the above also works when
```
<html>
    <frameset cols="*">
        <frame src="inner.html"></frame>
    </frameset>
<html>
```
as the outer frame/container.

**Comment by elondaits** [comment]
iFrames have many rendering / interaction bugs.... and even if those get eventually fixed surely more will arise. The performance hit might be related to HW acceleration according to a page I read.

... They're not a transparent solution.

The heartbeat should work simply by inserting a single <script> in the page. That <script> could perhaps be injected by electron by hooking on an event every time a page is loaded? (https://github.com/electron/electron/blob/master/docs/api/web-contents.md ?)

**Comment by elondaits** [comment]
PS: A proper solution should also not modify a page's URL because that might interfere with the regular operation of the web app.

**Comment by porst17** [comment]
If you don't provide init parameters to the heartbeat library directly, it will try determine them based on the URL query string. But this isn't something that should be discussed here.

Using the kiosk browser itself to inject something looks like a good idea. In this case, the heartbeat code could be added directly to the docker image.

**Comment by elondaits** [comment]
I'd fallback to a hardcoded domain name (heartbeat.hilbert.local ... local is a reserved TLD) and then point that to the actual heartbeat server using the hosts file or DNS. It could also be configured in electron, since electron "knows" about the heartbeat mechanism since it's injecting the script in the first place. It can inject it with the parameter it needs.

**Comment by porst17** [comment]
In docker (v1.8+), it would possible to add hosts to the `/etc/hosts` file when the container is started:
```
docker run --add-host heartbeat.hilbert.local:IP
```
Or via `compose` file:
```
extra_hosts:
 - "heartbeat.hilbert.local:IP"
```

**Comment by porst17** [comment]
Electron could inject the heartbeat JS library from the main thread via a data URI like so:
```JavaScript
var fs = require('fs');

fs.readFile('path/to/heartbeat.js', 'utf8', function(err, contents) {
    var contentsBase64 = Buffer.from(contents,'utf8').toString('base64');
    var dataURI = 'data:text/plain;base64,' + contentsBase64;
    myBrowserWindow.webContents.executeJavaScript(`
        var script = document.createElement('script');
        s.src = '${dataURI}';
        s.onLoad = function() { window.heartbeat = new Heartbeat(...); };
        document.documentElement.firstChild.appendChild(s);
    `);
});
```
The above code ECMA2015 code is untested, but it should work very similar to this.

The major drawback of injecting the code seems to me that we would need to inject the code again and again each time another page is loaded or the same page is reloaded.

I also didn't cover that the page this code is injected into should probalby finish loading before injecting anything.

Maybe the solution using frames (not `<iframe>`) is simpler. It only has to be done once and doesn't require any *code injection*:
```HTML
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Frameset//EN" "http://www.w3.org/TR/html4/frameset">
<html>
    <head>
        <script src="hilbert-heartbeat.js"></script>
        <script>
            document.write('<h1>HB messages should follow : </h1><br><hr>');
            var heartbeat = new Heartbeat();
        </script>
    </head>
    <frameset cols="*">
        <frame src="theMainPage.html" name="main">
    </frameset>
</html>
```
Do you see any major drawbacks with this? We shouldn't overcomplicate things ...

**Comment by elondaits** [comment]
Any solution with Frames should have all the same issues from one with iframes... I don't think they're going to have less bugs, or worse because they're almost not used anymore. Even if it's simpler now, it's harder to debug (or fix) if it generates issues.

I understand that electron has a thread for the electron process and another for the page rendering... which would be the better one, to make sure the app is running. It would be good to somehow hook into page navigation (via https://github.com/electron/electron/blob/master/docs/api/web-contents.md or something like that) to re-inject it if the user navigates to some other page, and a check should be done to make sure the document is top level (and not running in a frame/iframe).

I don't know about injecting a "data" blob... if it's going to have security limitations or not. Although the heartbeat can avoid CORS limitations in several ways, like requesting an image.

**Comment by porst17** [comment]
I see, your main concerns are bugs with (i)frames.

The injection has to be done from the main thread into the renderer thread. The main thread has to wait for the `onLoad` event of the page shown bei the renderer thread and then start the injection. And this has to be hooked into navigation as well, just like you said.

We can't really do anything about documents that utilize frames. This may be third-party content and removing the frames will probably have some negative side effect. Also, injecting the heartbeat into the innermost (i)frame might not mean anything. So I would just inject it into the top level.

Regarding the data blob: I need to inject JS code and this code needs to be loaded from somewhere. Using a data URI makes everything self contained, so I'd use that. But maybe it's not even necessary and I can load arbitrary JS objects from the main thread into the renderer threads, i.e. I could load the heartbeat JS library in the main thread and then attach the heartbeat library object to the `window` object of the renderer thread and call some methods on it. I have to test it.

**Comment by elondaits** [comment]
Bugs and performance... mainly because we may not notice the issues ourselves and because a bug would be hard to fix (or not possible at all) and then we'd have to remove the frame. Injecting a script seems like the solution of less impact, specially since it doesn't render anything.

**Comment by porst17** [comment]
The idea of loading the heartbeat script via frames has been dropped. Instead, it will be [preloaded into the kiosk browser](https://github.com/IMAGINARY/kiosk-browser/commit/6e05fe67de317b2d063c8b5d297cf25cdfe591c8). See also https://github.com/hilbert/hilbert-docker-images/issues/55 for the preload script.
